"""Corrige nome da tabela de refresh tokens para 'refresh'

Revision ID: 40f7c78333e4
Revises: b6cb35231785
Create Date: 2025-05-30 15:02:44.302389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f7c78333e4'
down_revision: Union[str, None] = 'b6cb35231785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
