"""Criar as tabelas iniciais

Revision ID: 5e42ca215557
Revises: 
Create Date: 2025-05-17 16:58:15.240618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e42ca215557'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fontes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('tipo_extracao', sa.String(length=15), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_fontes_id'), 'fontes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('noticias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('resumo', sa.String(length=300), nullable=False),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.Column('qtd_curtidas', sa.Integer(), nullable=True),
    sa.Column('data_postagem', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('id_fonte', sa.Integer(), nullable=False),
    sa.Column('data_coleta', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_fonte'], ['fontes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_noticias_id'), 'noticias', ['id'], unique=False)
    op.create_table('curtidas',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_noticia', sa.Integer(), nullable=False),
    sa.Column('data_curtida', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_noticia'], ['noticias.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_noticia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curtidas')
    op.drop_index(op.f('ix_noticias_id'), table_name='noticias')
    op.drop_table('noticias')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_fontes_id'), table_name='fontes')
    op.drop_table('fontes')
    # ### end Alembic commands ###
