"""Ajeitando os IDs das entidades

Revision ID: 7889ffbfff7a
Revises: 5e42ca215557
Create Date: 2025-05-18 09:17:23.106551

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '7889ffbfff7a'
down_revision: Union[str, None] = '5e42ca215557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
