"""Remove curtidas da tabela noticia

Revision ID: 8a2a2b125b4a
Revises: bf0439cdede5
Create Date: 2025-05-24 11:35:19.535449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2a2b125b4a'
down_revision: Union[str, None] = 'bf0439cdede5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noticias', 'qtd_curtidas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('qtd_curtidas', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
